name: project_akhir
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  google_fonts: 6.2.0
  font_awesome_flutter: ^10.1.0
  file_picker: ^8.0.3
  cookie_jar: ^4.0.8
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  carousel_slider: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/books/

fonts:
  - family: GravitasOne
    fonts:
      - asset: lib/users/assets/fonts/GravitasOne-Regular.ttf
  - family: Actor
    fonts:
      - asset: lib/users/assets/fonts/Actor-Regular.ttf
  - family: GothicA1
    fonts:
      - asset: lib/users/assets/fonts/GothicA1-Regular.ttf
